apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescale
    url: timescale:5432
    user: orc
    secureJsonData:
      password: $TIMESCALE_PASSWORD
    jsonData:
      database: orc
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: false
